### ISSUE TITLE
[Support]homebridge-cmd4 plugin required?

### ISSUE THREAD

**Issue by pocketscience** [uswong/homebridge-myplace#2]
**Describe Your Problem:**
Installed the my place plugin successfully, but when I try to create a configuration I get an error stating:

ERROR: no Cmd4 Config found in "/var/lib/homebridge/config.json"! Please ensure that Homebridge-Cmd4 plugin is installed

I installed the homebridge-cmd4 plugin, but that hasn't helped, and there's no information on what that plugin does or how to configure it.

**Comment by uswong** [comment]
No, you do not need to install "homebridge-cmd4".  "homebridge-myplace" is an independent plugin, it doesn't require any other plugin to run.  Please uninstall "homebridge-cmd4" in order for "homebridge-myplace" to run properly.

The error message you posted is not and cannot be from the latest version of "homebridge-myplace" plugin. Which version did u install?  Please install version 2.1.2 if not already.

Once installed, locate the "homebridge-myplace" plugin in homebridge UI, click on the three dots at the bottom right and select `JSON Config`, if it is newly installed you should see a pop-up box showing a small config in it.  It looks something like this:

     {
        "name": "MyPlace",
        "platform": "MyPlace"
     }

Do not edit anything in it but click `SAVE`.  More pop-up boxes may appear, click `SAVE` to all of them, until you are prompted to `RESTART` HOMEBRIDGE.  You do not need to restart homebridge at this point but click `CLOSE`.  

Then go back to the "homebridge-myplace" plugin, click the 3 dots on the bottom right corner again, now click "Plugin Config", then input your MyPlace system parameters, viz name, ipAddress, etc,  click `SAVE`.

Then, go back to the "homebridge-myplace" plugin, click the 3 dots on the bottom right corner one last time, click again "Plugin Config", then click on "Create Configuration", if it is a success, click `SAVE`, then `RESTART` Homebridge.

Please let me know if this resolves your issue.

**Comment by pocketscience** [comment]
OK, thanks. I removed everything and started again following your instructions. However when Homebridge restarts the myplace plugin fails. This is in the log:

```
[27/11/2024, 19:30:31] ====================
[27/11/2024, 19:30:31] ERROR LOADING PLUGIN homebridge-myplace:
[27/11/2024, 19:30:31] TypeError: Cannot redefine property: indexOfEnum
    at Function.defineProperty (<anonymous>)
    at Object.<anonymous> (/var/lib/homebridge/node_modules/homebridge-myplace/utils/indexOfEnum.js:8:23)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/var/lib/homebridge/node_modules/homebridge-myplace/lib/CMD5_ACC_TYPE_ENUM.js:5:19)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
[27/11/2024, 19:30:31] ====================
```

Other plugins load and operate OK (eg homebridge-ring - )

**Comment by uswong** [comment]
Have u uninstalled homebridge-cmd4?

**Comment by uswong** [comment]
You need to uninstall homebridge-cmd4 for homebridge-myplace to run properly. This is due to the fact that I have forked homebridge-cmd4 and used it as the accessories engine. As such if you also have homebridge-cmd4 running, a conflict will occur and you will see those error messages.

**Comment by uswong** [comment]
From v2.1.4 onwards, you may run `homebidge-cmd4` alongside this plugin.
